### PR TITLE
Run tests on CircleCI

### PR DESCRIPTION
**Pull request by sgerrand**
💁 Tests are great, especially for dynamic programming languages. These changes add an initial build configuration for CircleCI using the "latest and greatest" available versions of Clojure and Ruby.

### CODE REVIEW

**Comment by jesse-c** [comment]
@sgerrand: How did I never see this?! I've just updated this project so that it runs again and I'm looking at getting it live again.

**Comment by sgerrand** [comment]
Live to give. ™

**Comment by jesse-c** [comment]
Closing this (a million years later), as I adapted what you wrote via GitHub Actions. 🙇🏻

**Comment by sgerrand** [comment]
I'll take that as a win.

**Comment by jesse-c** [comment]
@sgerrand: Hopefully we get another win on Saturday

image

**Comment by sgerrand** [comment]
Sunday night should be a big one.

**Pull request closed without merging**
